dist: bionic
sudo: true
language: cpp
os: linux

addons:
  sonarcloud:
    organization: "jmramosr-github"
  apt:
    packages:
      - g++
      - gcc
      - make
      - lcov
      - gcovr

before_install:
  - pip install codecov
  - pip install gcovr

cache:
  apt: true
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/doxygen"
  - '$HOME/.sonar/cache'

script:
  - chmod +x ./lib/local_gtest_scripts/get-nprocessors.sh
  - chmod +x ./lib/local_gtest_scripts/travis.sh
  - chmod +x compile_part_1.sh
  - sh compile_part_1.sh
  - build-wrapper-linux-x86-64 --out-dir bw-output make
  - gcov -a -f -c -m -b ./obj/*.gcno -o ./obj/ -s ./src/
  - gcovr -g -k -r ./ --xml -o ./xml/coverage.xml
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

after_success:
  - codecov -t $CODECOV_TOKEN -X gcov
